version: '3.8'

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  backend:
    build: ./backend_hms
    env_file: .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend_hms:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend_hms
    env_file: .env
    command: npm run dev
    volumes:
      - ./frontend_hms:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge