# Generated by Django 4.2 on 2025-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
