# Generated by Django 4.2 on 2025-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='sub_title',
            field=models.CharField(max_length=40),
        ),
    ]
