# Generated by Django 4.2 on 2025-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_departments_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='sub_title',
            field=models.CharField(max_length=200),
        ),
    ]
