# Generated by Django 4.2 on 2025-03-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв на врача', 'verbose_name_plural': 'Отзывы на врачей'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='doctor_iin',
            new_name='doctor',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
