# Generated by Django 4.2 on 2025-04-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_options_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chronic_disease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
