# Generated by Django 4.2 on 2025-06-24 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('patient_iin', models.CharField(max_length=12, verbose_name='ИИН пациента')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('time', models.IntegerField(choices=[(1, '9:00-9:30'), (2, '9:30-10:00'), (3, '10:00-10:30'), (4, '10:30-11:00'), (5, '11:00-11:30'), (6, '11:30-12:00'), (7, '12:00-12:30'), (8, '12:30-13:00'), (9, '14:30-15:00'), (10, '15:00-15:30'), (11, '15:30-16:00'), (12, '16:00-16:30'), (13, '16:30-17:00'), (14, '17:00-17:30'), (15, '17:30-18:00')], verbose_name='Время приема')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('conclusion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заключение')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Лечение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Создана пациентом')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='department.department', verbose_name='Отделение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
                'db_table': 'appointments',
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
    ]
