# Generated by Django 4.2 on 2025-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='conclusion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заключение'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.TextField(blank=True, null=True, verbose_name='Лечение'),
        ),
    ]
