# Generated by Django 4.2 on 2025-04-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_description'),
        ('appointment', '0007_appointment_conclusion_appointment_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor', verbose_name='Врач'),
        ),
    ]
