# Generated by Django 4.2 on 2025-06-24 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Отделение')),
                ('sub_title', models.TextField(max_length=200, verbose_name='Описание')),
                ('link', models.CharField(max_length=40, verbose_name='Иконка')),
                ('doctors', models.ManyToManyField(related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Врачи')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'db_table': 'departments',
            },
        ),
    ]
