# Generated by Django 4.2 on 2025-03-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отделение', 'verbose_name_plural': 'Отделения'},
        ),
    ]
