# Generated by Django 4.2 on 2025-04-09 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='doctors',
            field=models.ManyToManyField(related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Врачи'),
        ),
        migrations.AlterField(
            model_name='department',
            name='link',
            field=models.CharField(max_length=40, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='department',
            name='sub_title',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Отделение'),
        ),
    ]
